### ISSUE TITLE
Kaikki on väärin

### ISSUE THREAD

**Issue by ghost** [ollpu/material-tempo#1]
Ihan hyödytön, pitää kääntää monta kertaa että toimii.

**Comment by ollpu** [comment]
Voisitteko avata vähän enemmän, mitä ongelmia teillä on sovelluksen kanssa? Muistutan, että sovellus on kehitysvaiheessa ja se saattaa olla epävakaa. 

(:smile:)

**Comment by ollpu** [comment]
Ongelmasi luultavasti johtuu siitä, että sinulla ei ole kaikkia vaadittuja SDK paketteja. Käytä SDK Manageria (Tools > Android > SDK Manager) asentaaksesi lisää paketteja.

**Comment by ollpu** [comment]
Closing issue for invalid & inactivity.
